apiVersion: v1
kind: Service
metadata:
    {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.ratings.namespace }}
spec:
  type: {{ .Values.ingress.serviceType }}
  ports:
  - port: {{ .Values.ratings.port }}
  selector:
    app: {{ .Release.Name }}